### ISSUE TITLE
Reimbursement process requirement

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#11]
@TDPS-Mihotel/project-manager Please

- [x] set up:
1. our reimbursement process
2. what information is neededd when they ask for budget from you

- [x] update those to repo Mihotel
:bulb: our budget should always updated there.

In that way every one are free to look for devices or circuits to buy ​:satisfied:​

**Comment by LiamBishop** [comment]
购买方名称: 电子科技大学
纳税人识别号:  121000004507193117
地址: 四川省成都市高新区(西区)西源大道2006号电子科技大学清水河校区
电话： 可填采购人电话
开户行及账号: 中国建设银行成都新鸿支行51001908608059000888 (非科研业务)

**Comment by LiamBishop** [comment]
The sum of money on the invoice should be matched to the transaction record of Alipay. In other word, the freight should be contained in the total price.
