### ISSUE TITLE
points to mention in report

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#2]
Let's leave comments in this issue to collect points to write in report 👍
@TDPS-Mihotel/document

**Comment by LeoJhonSong** [comment]
- our development strictly follows the V model

![image](https://user-images.githubusercontent.com/37630203/75734191-3eb4b680-5d32-11ea-97ed-07fa4eb4d986.png)

**Comment by shuchang** [comment]
* We employ the **Gantt chart** to manage the project schedule
![image.png](https://images.zenhubusercontent.com/5e5b67d6f4343397cf542a65/b2c925c4-f6bc-4272-aecc-4f122d70c984)

**Comment by LeoJhonSong** [comment]
Very good reference of what and how we can write in report :satisfied:

- [第十三届“恩智浦”杯全国大学生智能汽车竞赛技术报告-长春理工](https://bj.bcebos.com/cdstm-hyetecforthesmartcar-bucket/bb65363aa3ab442cb9732a7a95a943b0.docx)
- [第十三届“恩智浦”杯全国大学生智能汽车竞赛-厦门大学](https://bj.bcebos.com/cdstm-hyetecforthesmartcar-bucket/f9235095b5d04db2942fcec6d5e1ea44.pdf)

**Comment by LeoJhonSong** [comment]
Actually it is ridiculous that not even one report we saw has mentioned a single word about **teamwork** while this course is called `Team Design Project and Skills`. So I created a new issue #25 to collect teamwork contents we could talk about in our report.

**Comment by LeoJhonSong** [comment]
We use git to  control the version of our code, hosting on github, which provide us with a lot of additional features and third party services, such as ZenHub.

**Comment by LeoJhonSong** [comment]
我觉得应该说一下我们对信息的使用的准则: [关于如何使用传感器算是合理的](https://github.com/tdps-mihotel/mihotel/issues/55#issuecomment-628147856)

规定好这个才能谈后续的, 不然很多事情不知道是不是做过界了. 规定了这个才好说我们如何利用规则设计的我们的解决方案.

**Comment by LeoJhonSong** [comment]
@TDPS-Mihotel 大家来集思广益啊 :muscle:

**Comment by LeoJhonSong** [comment]
线上协作开发让我们有机会接触这种先设计, 仿真然后才进行实物测试的模式. (虽然我们没有最后一步) 在我们的讨论中可以发现当我们从零开始设计时这样做是最高效, 有方向性的:
- 给出项目的定位
- 定下项目的规格, 技术指标
- 根据这个总的指标分解为各部分的指标
- 根据指标选型, 查找参考资料, 给出可能解决方案
- 测试解决方案, 调整解决方案

实际上这正是个V-model的具体例子. 如果我们不给自己设定技术指标那么在开发过程中随时有可能产生不合理的设计, 不必要的困扰. 退一步讲也会导致团队内沟通不畅, 信息混乱. 而如果不根据技术指标来设计解决方案那很容易找不到切入点, 迷失方向, 或者做出看似符合要求实则无效的解决方案, 很容易浪费时间.
而在有了多个解决方案时很容易纠结与选择哪个解决方案, 这时不应该浪费时间讨论, 应该让各小组实现解决方案, 进行仿真/实物实验测试哪个方案效果好. 对工程来说一切以效果为准.
