### ISSUE TITLE
Visual-Path following course detection algorithm development

### ISSUE THREAD

**Issue by wb05025** [TDPS-Mihotel/Mihotel#32]
Patio1-task1: From the start, follow the path to the bridge
Purpose: to detect the path to be followed, its direction and return correction angle. 
We will try both machine learning methods and regular image processing methods.

The goal is to detect the course with no error in general direction and error as small as possible in specific angle.

Difficulty: Unclean surface disturbance\shadow of the car\more accurate calculation in curve segments.

First try by regular IP methods:
![path1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/5e7e38af-26b4-42b7-9d63-ae78670eea72)!
[path2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/00d1fffa-a7f1-4c98-8c4f-22a4005acf44)!
[path3.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/72d76a55-4a20-4761-8ba8-1a03efd543a7)
![path4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/cb5d448e-310a-4f00-9fe6-eb5f75b3391d)
![path5.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/c1d1ca5d-91c8-45d8-b9d5-757b3e0eb482)

MATLAB script:
[https://app.zenhub.com/files/243200095/8d2589e8-6ff7-4e8f-9f14-b31649803dba/download](https://app.zenhub.com/files/243200095/8d2589e8-6ff7-4e8f-9f14-b31649803dba/download)

**Comment by wb05025** [comment]
![path3.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/1c396b9f-fa57-4bd4-8222-6139695f3217)
![path2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/225a5d8a-71ac-4491-a232-51d4d11c23ab)

**Comment by wb05025** [comment]
New MATLAB script with minor fix and annotation
[https://app.zenhub.com/files/243200095/f1dee83a-ca12-4726-83c5-39c7944e7ce7/download](https://app.zenhub.com/files/243200095/f1dee83a-ca12-4726-83c5-39c7944e7ce7/download)

**Comment by LeoJhonSong** [comment]
I suggest you create a more specific epic (which belongs to the Visual Development epic)  for this **path recognition** topic
