### ISSUE TITLE
car modeling

### ISSUE THREAD

**Issue by Howard2503** [TDPS-Mihotel/Mihotel#35]

**Comment by LeoJhonSong** [comment]
please update the status of this issue.

**Comment by LeoJhonSong** [comment]
![image](https://user-images.githubusercontent.com/37630203/79935831-744f6380-8488-11ea-8c86-b0ef52719799.png)

It seems [SolidWorks could export VMRL 2.0 file](https://help.solidworks.com/2017/english/SolidWorks/sldworks/HIDD_EXPORT_OPTIONS_VRML.htm).
You may have a try.

**Comment by Howard2503** [comment]
the model we used seem to have to many components which require me to assign their properties seperately. And scaling in webots cause unexpected problems. I am looking for a solution

**Comment by LeoJhonSong** [comment]
[This](https://jingyan.baidu.com/article/d169e1864cc54e436611d832.html) may helps you. You can merge most components into, say just body and four wheels.

**Comment by Howard2503** [comment]
thanks I will try this
