### ISSUE TITLE
Notebook & Report & PPT & Video

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#4]

**Comment by wb05025** [comment]
(https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/9b8b1678-2980-45dd-a266-590b28f1bd61)
![path5.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/8ca19bc2-c77f-41d8-a6c2-c1c015f29c66)
![path4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/f822f446-961a-4a4d-b576-0fa0ee856e58)
![path1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/15e0af02-58fc-4bf2-aa2a-204291ab2b60)

![直4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/e73370aa-7360-4b4c-b914-fe8a0fb5c0d8)
![右2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/c6b19c66-947a-43a0-9680-69e484a40a86)
![左2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/5d117e56-48b1-43a3-bb7d-520c293f44e9)

![右+阴影.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/cd93d078-1f8b-406b-8f7e-a39db7d28bfa)
![左+阴影.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/174de103-8e64-4968-a379-86818e400255)
![直+阴影.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/70564909-9e3e-478d-b2e3-e20df9a15d4f)
![寻找路径入口4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/60b6d622-8047-4282-b796-a35478a3420e)
![寻找路径入口2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/b6d5f28f-c5e3-48c0-9e61-3f15a305f586)
![无+阴影.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/3d38bc6f-7a9f-4f65-aa23-32b17347f46b)




![b1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/81de2434-b40c-4e33-b169-bbbe5340431a)
![b3.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/7c75a2c4-f9f3-40bc-9779-0cee575f3130)
![b5.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/865c9d86-877f-4146-9eeb-13bcc7d4fbab)
![b7.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/48224ba0-8348-4374-8374-819b6bffaaca)

![gi1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/115cc4dd-40f9-48a3-ac84-04ae67c9f112)
![gi2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/8b6b8624-3888-422e-899a-84fee9d60658)
![gi4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/5f1f4ce5-367b-4904-babe-ce13a8b0c8a6)
![gi7.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/3c8d6741-70d0-4aca-9ad0-d16732f4ff10)
![gi9.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/eacdd4b5-2c1c-4690-a1d1-5eadab389b18)

![ppt3.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/4f3453c2-7602-42f3-8b18-31ecf580f6cd)
![ppt1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/6bcd1475-a2a4-4d89-9e69-4d64ec1d3335)
![ppt2.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/4b9253f6-b285-46c7-bc02-383b1c6a7138)
![ppt4.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/c585d0f5-85c3-49e9-b3d9-7b40c46e9926)
![ppt5.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/66ba9ec8-819b-492a-b753-228b9ef12c91)
![ppt6.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/362e63d0-9bcb-493f-9c56-fada3c84b454)



![ti1.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/d0d5cb6a-cb98-4362-b569-485e1e3fe0be)
![ti3.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/5ffe2748-b93b-432a-8819-158c13f985c6)
![ti5.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/9a013b64-c624-4686-bc6b-b8256443e350)
![ti6.JPG](https://images.zenhubusercontent.com/5e70d3478ec11b0fa1ec205a/7604a03e-6b77-40ec-b5a8-ff71df3469c2)
