### ISSUE TITLE
Realizing path recognition algorithm in Webots

### ISSUE THREAD

**Issue by shuchang** [TDPS-Mihotel/Mihotel#47]
The current task includes two parts
* apply the first path recognition algorithm in Webots to get a baseline
* try to realize color detection and object detection (trees, beacons) in Webots

After it is finished, we can start to work on other path recognition algorithms to obtain better performance than the baseline

**Comment by LeoJhonSong** [comment]
Is this implemented? Could we close it?

**Comment by shuchang** [comment]
@HandAdam is translating the Matlab code into Python and I will polish the codes
