### ISSUE TITLE
image captured are not in right direction

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#63]
摄像头实际拍摄到的画面是下图这样的
![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/6f135c24-69f9-4513-a3a4-a6cf749f9964)
但保存出来的图片是这样的
![2020-05-13-04-17-13test.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/d4329c01-b521-4e12-a76a-d10a56b280b8)

这个方向没对, 需要你修一下:+1:

另外右边的estimate point记得设置一下.

P.S. 要拍照的话要鼠标点一下3D场景的窗口, 确保在那个里面, 然后不能就敲一点C, 不太确定是我程序写得不够好还是它本身就没有那么灵敏, 你就按着C直到看到输出里有个**Captured! 📸**好了. (这句本来是绿色的, 比较显眼, 但因为彩色输出在Windows似乎还有点bug... 暂时忍一下)

**Comment by LeoJhonSong** [comment]
另外原本我的想法是让他保存在这里 (如下图) 的, 结果疏忽了, 写成保存在`webots/controller/mihotel_rover/test/camera/0/`下面了... 我在[]()里把这个路径改过来了.

另外我建议可以把这个函数再封装好一些, 比如:
```python
    def capture(self, index):
        '''
        capture images from camera to test/camera/.
        '''
        capture_path = '../../../test/camera/' + str(index)
        if not os.path.exists(capture_path):
            os.makedirs(capture_path)
        image = self.get_image(index)
        cv2.imwrite(capture_path + time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + '.png', image)
        info('Captured!')
```
这样可以把对应相机的图片存到对应index的文件夹下, 调用也容易一些, 直接`self.capture(3)`就可以.

**Comment by Han-Adam** [comment]
![1.png](https://images.zenhubusercontent.com/5e5e045cbf668358438d1902/1d414a9a-739f-4d19-921d-bc1fc5b9aad1)


xxxx
![2.png](https://images.zenhubusercontent.com/5e5e045cbf668358438d1902/198c3a07-9dd6-40dd-84a4-02d2fbf08ca5)


xxx
![3.png](https://images.zenhubusercontent.com/5e5e045cbf668358438d1902/8e65f4b9-6fb7-45f3-ad78-98eb28576472)
