### ISSUE TITLE
Let's select a ASCII art logo😏

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#7]
It will be used in ssh connection and also transmitted message in p2t3.

 :link: find a "Mihotel" in fancy font [here](http://patorjk.com/software/taag/#p=display&f=Acrobatic&t=Mihotel)

Let's leave comments to select one :+1:

some good one I found:

- 3D Diagonal

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/a919bcff-dd55-4cc8-8480-6df006bfe9a2)

- Star Wars

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/85265e7e-8784-43b1-b6f6-aad70d998ba8)

- Roman

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/b62c761c-ff24-40bb-b683-3cb5ab4e9a95)

- Reverse

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/af92b5a5-aa16-48e8-b58d-2b5bf417b569)

- alpha

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/649de41c-41e8-4db6-87c3-1a77bb18ba7c)

**Comment by LeoJhonSong** [comment]
Font Name: ANSI Shadow

![image.png](https://images.zenhubusercontent.com/5e561721d0668b3a20133dfa/885d9fb5-bb9a-4d97-89e1-bb5d1fa260f1)

**Comment by Prince-JIAN** [comment]
Calvin S
![1.png](https://images.zenhubusercontent.com/5e5d1de8c9cab6b744a30db6/1d474a5b-26cb-454a-9bf5-eb5e60f8d425)

**Comment by LeoJhonSong** [comment]
OK, I'll pick my modified version of **Big Money-ne**, code is here:

```
     /██      /██ /██ /██                   /██               /██
    | ███    /███|__/| ██                  | ██              | ██
    | ████  /████ /██| ███████   /██████  /██████    /██████ | ██
    | ██ ██/██ ██| ██| ██__  ██ /██__  ██|_  ██_/   /██__  ██| ██
    | ██  ███| ██| ██| ██  \ ██| ██  \ ██  | ██    | ████████| ██
    | ██\  █ | ██| ██| ██  | ██| ██  | ██  | ██ /██| ██_____/| ██
    | ██ \/  | ██| ██| ██  | ██|  ██████/  |  ████/|  ███████| ██
    |__/     |__/|__/|__/  |__/ \______/    \___/   \_______/|__/

 ```
It taste good in terminal
![image](https://user-images.githubusercontent.com/37630203/78739653-4eee3000-7987-11ea-9636-7895a2db05ee.png)
