### ISSUE TITLE
give the value range of colors we concerned

### ISSUE THREAD

**Issue by shuchang** [TDPS-Mihotel/Mihotel#72]
The color detection module should be able to distinguish the colors of the following objects. Here I make a rough division.
* blue: the pond, the river, and the sky, the color box
* red: the color box
* green: the color box
* orange: the orange box
* yellowish-brown: the sand

**Comment by LeoJhonSong** [comment]
No, I think we just have to **focus on our interested colors**, pixels in other color should be simply filtered, for example the color of pond, river or sky is now not our interest.

Our interest colors now are:
- **red** of colored box and line
![image](https://user-images.githubusercontent.com/37630203/82123478-41209b80-97cc-11ea-860b-6f9066fdd7b3.png)
- **yellow** of colored box and line
![image](https://user-images.githubusercontent.com/37630203/82123492-55fd2f00-97cc-11ea-8c63-d263d5952720.png)
- **purple** of colored box and line
![image](https://user-images.githubusercontent.com/37630203/82123499-62818780-97cc-11ea-9898-687ec232d4e5.png)
- **orange** of orange box
![image](https://user-images.githubusercontent.com/37630203/82123512-79c07500-97cc-11ea-9584-e6817bfbf5e8.png)

So what you need to do is operating the source image with the masks you designed, to see if there are pixels of these colors. If there is, we get a target.

:exclamation: Note that Wasim did not specify the exact color values :smirk: so if the yellow line on sand ground is difficult to recognize, you could choose a **specific yellow** which makes it easier. Or, if it is still too difficult, ask the environment group to place a white plane under the lines in task5.

**Comment by shuchang** [comment]
Oops, I was thinking the three colors in Task 5 are red, green, blue. 
If I get it right, I need to specify the range of these four colors and change the program from finding the principal color into giving a signal once we find a color we want. No problem!

**Comment by LeoJhonSong** [comment]
Exactly.

**Comment by LeoJhonSong** [comment]
[Here](https://github.com/jrosebr1/imutils/blob/master/bin/range-detector) is a script which helps you to find the threshold with **GUI** and **real-time**.
Just copy the content of this script to a file enjoy!
An example to run this script:
```shell
python range-detector.py -f HSV --image ./test.png
```

**Comment by LeoJhonSong** [comment]
> I need to specify the range of these four colors and change the program from finding the principal color into giving a signal once we find a color we want.

I suppose [this](https://www.pyimagesearch.com/2014/08/04/opencv-python-color-detection/) could help you to do that.

**Comment by shuchang** [comment]
It seems that fine-tuning the threshold with GUI does not bring about satisfactory results.  I can only find a broad range with this approach,  which causes other colors to be recognized as target color as well. 
I suggest using the Snipaste to find the accurate R, G, B values of the target color and set the range with a little tolerance.

**Comment by LeoJhonSong** [comment]
> It seems that fine-tuning the threshold with GUI does not bring about satisfactory results. I can only find a broad range with this approach, which causes other colors to be recognized as target color as well.

Noise reduction is really an art. You may have to search a lot to figure out some filter method that helps impproving you recognition. Best Wishes. :muscle:

**Comment by LeoJhonSong** [comment]
要注意因为阿韩的算法是将颜色较深的像素作为路面, 因此你应当将要滤掉的像素值设为白色
