### ISSUE TITLE
Start chassis development

### ISSUE THREAD

**Issue by LeoJhonSong** [TDPS-Mihotel/Mihotel#9]
@TDPS-Mihotel/Chassis Please create a repo **from your team page** (therefore it belongs to your team) for your chassis development.

Items in this repo could be:

- 3D model files of the whole rover
- documents of chassis development so everyone can know your work
- code of chassis
- main references of each device provided by taobao

Then grub a platform from taobao now. Remember to send the invoice to @TDPS-Mihotel/project-manager

**Comment by LeoJhonSong** [comment]
Observing how other chassis arrange all the components may helps:+1:

![TIM图片20200309124938](https://user-images.githubusercontent.com/37630203/76183794-a4a6af80-6204-11ea-8cb8-c73b7e0ff473.jpg)
![TIM图片20200309124951](https://user-images.githubusercontent.com/37630203/76183821-bb4d0680-6204-11ea-8c76-c5125661eb47.jpg)
![TIM图片20200309124958](https://user-images.githubusercontent.com/37630203/76183828-bf792400-6204-11ea-8e4a-e23bb31aa33c.jpg)
![image](https://user-images.githubusercontent.com/37630203/76183768-935da300-6204-11ea-89ba-3eb5ee1594ec.png)

**Comment by Howard2503** [comment]
chassis model modification
